import type { NextPage } from "next"
import Head from "next/head"
import { Button } from "../components/buttons"
import { Container } from "../components/container"
import { StartBar } from "../components/startBar"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Windows 95 Components</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container>
        <h1 className="underline">Windows 95 Components</h1>
        <Button width={"tight"}>Tight button</Button>
        <Button width={"wide"}>Wide button</Button>
        <StartBar />
      </Container>
    </>
  )
}

export default Home
