import type { NextPage } from "next"
import Head from "next/head"
import { Container } from "../components/container"
import { StartBar } from "../components/startBar"

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Windows 95 Components</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container />
      <StartBar />
    </>
  )
}

export default Home
